Repository Josieljcc/info-os-fontend, pull requests merged in 2025-01, with the labels that each got.

#4 Implementação da Rota de Registro de Cliente e Integração com Backend
  components.json
  package-lock.json
  package.json
  src/Pages/home.tsx
  src/Pages/login.tsx
  src/Pages/registerTechnician.tsx
  src/Routes/router.tsx
  src/components/buttonPrimary/buttonPrimary.tsx
  src/components/formClient/formClient.tsx
  src/components/formDrawer/formDrawer.tsx
  src/components/ui/drawer.tsx
  src/hook/useRegister.tsx
  src/index.css
  src/lib/utils.ts
  src/schemas/registerClient.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: enhancement

#5 fix: drawer style
  src/Pages/login.tsx
  src/Pages/registerTechnician.tsx
  src/components/formClient/formClient.tsx
  src/components/formDrawer/formDrawer.tsx
  src/components/ui/drawer.tsx
Labels: bug

#7 Configuração de Deploy Automático com GitHub Actions e Docker
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
  public/assets/logoInfos.png
  public/assets/logoInfosWhite.png
  public/assets/main.png
  src/Pages/login.tsx
  src/Pages/registerTechnician.tsx
  src/components/SecondaryBackground/SecondaryBackground.tsx
  tailwind.config.js
Labels: infra

#6 Create part form and back end integration
  src/Pages/home.tsx
  src/components/formPart/formPart.tsx
  src/hook/useRegister.tsx
  src/schemas/parts.ts
Labels: enhancement

#9 fix: create redirect register
  src/Pages/login.tsx
  src/Pages/registerTechnician.tsx
Labels: bug, enhancement
