Repository Josieljcc/info-os-fontend, pull requests merged in 2025-10, with the labels that each got.

#62 Fix Os register
  package-lock.json
  package.json
  src/components/ClientSearchDropdown/ClientSearchDropdown.tsx
  src/components/MultiSelectDropdown/multiSelectDropdown.tsx
  src/components/MultiSelectDropdown/multiSelectPart.tsx
  src/components/datePicker/datePicker.tsx
  src/components/formOrder/formOrder.tsx
  src/components/input/input.tsx
  src/components/sideBar/constants.tsx
  src/components/ui/calendar.tsx
  src/hook/useFormOrder/useFormOrder.tsx
  src/hook/useOrder.tsx
  src/schemas/equipment.ts
  src/schemas/order.ts
  src/schemas/parts.ts
  src/schemas/registerClient.ts
  src/schemas/registerTechnician.ts
  src/schemas/services.ts
  src/types.ts
  yarn.lock
Labels: bug, enhancement

#65 fix: update branch name from 'main' to 'master' in staging deployment
  .github/workflows/staging.yml
Labels: bug, infra

#67 fix: fixes package lock
  package-lock.json
  yarn.lock
Labels: bug
