Repository Josieljcc/info-os-fontend, pull requests merged in 2025-08, with the labels that each got.

#41 Delete technician
  src/components/Cards/CardUser.tsx
  src/hook/useTechnician/useTechnician.tsx
Labels: enhancement

#42 Delete part
  src/components/Cards/CardPart.tsx
  src/components/Cards/CardUser.tsx
  src/components/deleteButton/deleteButton.tsx
  src/hook/usePart.tsx
Labels: enhancement

#44 fix: search querykey
  src/hook/useClient/useSearchClient.tsx
  src/hook/usePart.tsx
  src/hook/useSearchByName.tsx
  src/hook/useTechnician/useSearchTechnician.tsx
Labels: bug

#38 Create detail parts
  src/Pages/detailTechnicianPage.tsx
  src/Pages/listPart.tsx
  src/Routes/router.tsx
  src/components/Cards/CardPart.tsx
  src/components/Cards/CardUser.tsx
  src/components/EditForm/editClientForm.tsx
  src/components/EditForm/editPartForm.tsx
  src/components/EditForm/editTechnicianForm.tsx
  src/components/detailComponent/detailPart.tsx
  src/components/detailComponent/detailUser.tsx
  src/components/detailForm/clientForm.tsx
  src/components/detailForm/partForm.tsx
  src/components/detailForm/technicianForm.tsx
  src/components/detailModal/partModal.tsx
  src/components/detailModal/userModal.tsx
  src/components/formPart/formPart.tsx
  src/hook/useFormOrder/useFormOrder.tsx
  src/hook/usePart/useEditPart.tsx
  src/hook/usePart/useGetPart.tsx
  src/hook/usePart/usePart.tsx
Labels: enhancement

#39 Create detail service
  src/Pages/listService.tsx
  src/components/Cards/CardService.tsx
  src/components/EditForm/editServiceForm.tsx
  src/components/detailComponent/detailService.tsx
  src/components/detailForm/serviceForm.tsx
  src/components/detailModal/serviceModal.tsx
  src/components/formService/formService.tsx
  src/hook/Service/useEditService.tsx
  src/hook/Service/useGetService.tsx
  src/hook/Service/useService.tsx
Labels: enhancement

#40 Create detail equipment
  src/Pages/listEquipment.tsx
  src/components/Cards/CardEquipment.tsx
  src/components/EditForm/editEquipment.tsx
  src/components/detailComponent/detailEquipment.tsx
  src/components/detailForm/equipment.tsx
  src/components/detailModal/equipmentModal.tsx
  src/hook/useEquipment/useEditEquipment.tsx
  src/types.ts
Labels: enhancement

#47 Delete service
  src/Pages/listService.tsx
  src/components/Cards/CardService.tsx
  src/components/EditForm/editServiceForm.tsx
  src/components/formService/formService.tsx
  src/hook/useService/useDeleteService.tsx
  src/hook/useService/useEditService.tsx
  src/hook/useService/useGetService.tsx
  src/hook/useService/useService.tsx
Labels: enhancement

#50 Update Dockerfile to use Alpine versions and configure nginx to run as non-root user
  Dockerfile
Labels: infra, Security
