Repository Josieljcc/info-os-fontend, pull requests merged in 2025-05, with the labels that each got.

#18 Detail client
  src/Pages/detailClientPage.tsx
  src/Pages/listClient.tsx
  src/Routes/router.tsx
  src/components/clientDetail/clientDetail.tsx
  src/components/editClientForm/editClientForm.tsx
  src/hook/useClient.tsx
  src/schemas/editing.ts
Labels: enhancement

#17 Implementar funcionalidade de busca de clientes com filtros e tipos
  package-lock.json
  package.json
  src/Pages/detailClientPage.tsx
  src/Pages/listClient.tsx
  src/components/editClientForm/editClientForm.tsx
  src/components/formClient/formClient.tsx
  src/components/formEquipment/formEquipment.tsx
  src/hook/useClient/types.ts
  src/hook/useClient/useClient.tsx
  src/hook/useClient/useSearchClient.tsx
  src/hook/useFormOrder.tsx
Labels: enhancement

#21 Fixes list client in order form, create a search client component
  package-lock.json
  package.json
  src/Pages/listClient.tsx
  src/components/ClientSearchDropdown/ClientSearchDropdown.tsx
  src/components/formOrder/formOrder.tsx
  src/components/ui/popover.tsx
  src/hook/useClient/useClient.tsx
  src/hook/useClient/useSearchClient.tsx
  src/hook/useDebounce/useDebounce.tsx
  src/hook/useFormOrder.tsx
  src/schemas/order.ts
Labels: bug, enhancement, refactor

#19 Fix list technician and create infinite scroll
  package-lock.json
  package.json
  src/Pages/listTechnician.tsx
  src/components/Card/Card.tsx
  src/components/backPageButton/backPageButton.tsx
  src/hook/useClient/useClient.tsx
  src/hook/useResizeObserver.tsx
  src/hook/useRowVirtualizer.tsx
  src/hook/useTechnician.tsx
Labels: bug, enhancement

#25 List part
  src/Pages/home.tsx
  src/Pages/listPart.tsx
  src/Routes/router.tsx
  src/components/Cards/CardPart.tsx
  src/hook/useClient/useClient.tsx
  src/hook/useOrder.tsx
  src/hook/usePart.tsx
  src/hook/useTechnician.tsx
  src/types.ts
Labels: enhancement

#23 Home navegation base
  src/Pages/home.tsx
  src/Pages/listClient.tsx
  src/Pages/listTechnician.tsx
  src/Pages/order.tsx
  src/Routes/router.tsx
  src/components/sideBar/constants.tsx
  src/components/sideBar/sideBar.tsx
  src/components/sideBar/sideBarItem.tsx/sideBarItem.tsx
  src/components/sideBar/types.ts
  src/hook/useLogin.tsx
  src/hook/useRowVirtualizer.tsx
  src/layout.tsx
Labels: enhancement

#27 Style dashboard client and refactor client list
  package-lock.json
  package.json
  src/Pages/detailClientPage.tsx
  src/Pages/listClient.tsx
  src/Pages/login.tsx
  src/Pages/registerTechnician.tsx
  src/components/Cards/CardUser.tsx
  src/components/buttonPrimary/buttonPrimary.tsx
  src/components/drawerClient/drawerClient.tsx
  src/components/formClient/formClient.tsx
  src/components/formDrawer/formDrawer.tsx
  src/components/formEquipment/formEquipment.tsx
  src/components/input/input.tsx
  src/components/searchInput/searchInput.tsx
  src/components/sideBar/sideBar.tsx
  src/components/ui/drawer.tsx
  src/hook/useClient/useClient.tsx
  src/hook/useClient/useGetClient.tsx
  src/index.css
  src/layout.tsx
  src/types.ts
  tailwind.config.js
Labels: enhancement, refactor

#29 feat: create general hook for search name
  src/hook/useSearchByName.tsx
Labels: enhancement
